import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "../globals.css";

import { cn } from "@/lib/utils"
import OpenFlag from "@/components/openFlag";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body 
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
            <header>
                <h1>Portal Game</h1>
                <OpenFlag></OpenFlag>
            </header>
            {children}</body>
    </html>
  );
}
